name: 'Packer EC2'
description: 'AMI Builder'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-region:
    description: 'AWS AMI Region'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  build:
    description: 'Packer build name'
    required: true
  instance-type:
    description: 'AWS EC2 Instance Type'
    required: true
    default: 't3.micro'
  packer-directory:
    description: 'Packer directory'
    required: false
  packer-version:
    description: 'Packer version'
    required: false
    default: '1.7'
  subnet-id:
    description: 'AWS Subnet ID. Export to environment variable `PKR_VAR_SUBNET_ID`'
    required: true
  var-file:
    description: 'Packer var file'
    required: false
    default: 'none'
  vpc-id:
    description: 'AWS VPC ID. Export to environment variable `PKR_VAR_VPC_ID`'
    required: true
outputs:
  ami-id:
    description: 'AMI ID'
    value: ${{ steps.build-ami.outputs.ami-id }}
  aws-region:
    description: 'AWS AMI Region'
    value: ${{ steps.build-ami.outputs.aws-region }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: false

    - name: Setup Packer
      uses: hashicorp/setup-packer@v3.0.0
      with:
        version: ${{ inputs.packer-version }}

    - name: Run `packer init`
      id: init
      shell: bash
      working-directory: ${{ inputs.packer-directory }}
      run: packer init .

    - name: Run `packer validate`
      id: validate
      shell: bash
      env:
        PKR_VAR_instance_type: ${{ inputs.instance-type }}
        VAR_FILE: ${{ inputs.var-file }}
      working-directory: ${{ inputs.packer-directory }}
      run: |
        # Output the subnet and vpc ids
        echo "Subnet ID: $PKR_VAR_SUBNET_ID"
        echo "VPC ID: $PKR_VAR_VPC_ID"

        if [ "$VAR_FILE" = "none" ]
        then
          packer validate \
            -var region=${{ inputs.aws-region }} \
            -only ${{ inputs.build }} \
            .
        else
          packer validate \
            -var region=${{ inputs.aws-region }} \
            -var-file ${{ inputs.var-file }} \
            -only ${{ inputs.build }} \
            .
        fi

    - name: Run `packer build`
      id: build-ami
      shell: bash
      working-directory: ${{ inputs.packer-directory }}
      env:
        PKR_VAR_instance_type: ${{ inputs.instance-type }}
        VAR_FILE: ${{ inputs.var-file }}
      run: |
        if [ "$VAR_FILE" = "none" ]
        then
          packer build \
            -color=false \
            -machine-readable 
            -on-error=abort \
            -var region=${{ inputs.aws-region }} \
            -only ${{ inputs.build }} \
            .
        else
          packer build \
            -color=false \
            -machine-readable \
            -on-error=abort \
            -var region=${{ inputs.aws-region }} \
            -var-file ${{ inputs.var-file }} \
            -only ${{ inputs.build }} \
            .
        fi
